version: 2
jobs:
   build:
     docker:
       - image: koppor/texlive
     steps:
       - checkout
       - run: latexmk main-german.tex
       - run: latexmk main-minted-german.tex
       - run: latexmk main-english.tex
       - run: latexmk main-paderborn-german.tex
       - run: latexmk main-paderborn-english.tex
       - run: mkdir build && cp -r README.md main-*.pdf .github/_config.yml docs/* build/
       - run: if [ "$CIRCLE_BRANCH" == "master" ]; then .circleci/deploy-ghpages.sh build/; fi
