name: Build with lualatex (and publish to gh-pages)
on:
  push:
  pull_request:
  schedule:
    - cron: '1 2 2,16 * *'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile main-german.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main-german.tex
          args:
      - name: Compile main-minted-german.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main-minted-german.tex
          args:
      - name: Compile main-english.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main-english.tex
          args:
      - name: Compile main-paderborn-german.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main-paderborn-german.tex
          args:
      - name: Compile main-paderborn-english.tex
        uses: dante-ev/latex-action@latest
        with:
          root_file: main-paderborn-english.tex
          args:
      - name: Gather build artifacts
        run: mkdir build && cp -r main-*.pdf .github/_config.yml docs/* build/
      - name: Deploy
        if: github.ref == 'refs/heads/master'
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: gh-pages
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
